### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by gangliao** [DSL-UMD/hadoop#142]

**Comment by gangliao** [comment]
original hadoop: https://github.com/DSL-UMD/docs/blob/master/src/bench/hdfs.md

**Comment by gangliao** [comment]
-[x] original hdfs benchmark.
-[ ] hopsfs

**Comment by gangliao** [comment]
https://github.com/DSL-UMD/docs/blob/master/src/bench/hopsfs.md

**Comment by gangliao** [comment]
HopFS on a single node is very slow.  When I tried to open 100000 files, it's also out of memory.

```bash
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:695)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at com.mysql.clusterj.tie.FixedByteBufferPoolImpl.borrowBuffer(FixedByteBufferPoolImpl.java:102)
	at com.mysql.clusterj.tie.NdbRecordImpl.newBuffer(NdbRecordImpl.java:299)
	at com.mysql.clusterj.tie.NdbRecordOperationImpl.allocateValueBuffer(NdbRecordOperationImpl.java:329)
	at com.mysql.clusterj.tie.NdbRecordScanOperationImpl.nextResultCopyOut(NdbRecordScanOperationImpl.java:232)
	at com.mysql.clusterj.tie.NdbRecordScanResultDataImpl.next(NdbRecordScanResultDataImpl.java:128)
	at com.mysql.clusterj.core.query.QueryDomainTypeImpl.getResultList(QueryDomainTypeImpl.java:183)
	at com.mysql.clusterj.core.query.QueryImpl.getResultList(QueryImpl.java:146)
	at io.hops.metadata.ndb.wrapper.HopsQuery.getResultList(HopsQuery.java:46)
	at io.hops.metadata.ndb.dalimpl.hdfs.INodeClusterj.findInodesPPISTx(INodeClusterj.java:479)
	at io.hops.metadata.adaptor.INodeDALAdaptor.findInodesPPISTx(INodeDALAdaptor.java:94)
	at org.apache.hadoop.hdfs.server.namenode.AbstractFileTree$ChildCollector$1.performTask(AbstractFileTree.java:115)
	at io.hops.transaction.handler.LightWeightRequestHandler.execute(LightWeightRequestHandler.java:56)
	at io.hops.transaction.handler.RequestHandler.handle(RequestHandler.java:68)
	at org.apache.hadoop.hdfs.server.namenode.AbstractFileTree$ChildCollector.run(AbstractFileTree.java:170)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
