### ISSUE TITLE
[BUG] Proxy layer

### ISSUE THREAD

**Issue by gangliao** [DSL-UMD/hadoop#162]
Namenode:

```bash
gangl@linuxkit-025000000001:~/hadoop/hadoop-dist/target/hadoop-3.3.0-SNAPSHOT$ ./bin/hadoop org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark -fs hdfs://localhost:65212 -op create -threads 1 -files 100 -filesPerDir 100 -keepResults -logLevel INFO
2019-09-06 05:12:30,973 ERROR namenode.NNThroughputBenchmark: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.RpcNoSuchProtocolException): Unknown protocol: org.apache.hadoop.hdfs.server.protocol.NamenodeProtocol
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.getProtocolImpl(ProtobufRpcEngine.java:444)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:502)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:906)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:852)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1876)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2753)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1516)
	at org.apache.hadoop.ipc.Client.call(Client.java:1462)
	at org.apache.hadoop.ipc.Client.call(Client.java:1372)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy11.versionRequest(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.NamenodeProtocolTranslatorPB.versionRequest(NamenodeProtocolTranslatorPB.java:162)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.getBlockPoolId(NNThroughputBenchmark.java:1558)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.run(NNThroughputBenchmark.java:1531)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.runBenchmark(NNThroughputBenchmark.java:1438)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.main(NNThroughputBenchmark.java:1563)

Exception in thread "main" org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.RpcNoSuchProtocolException): Unknown protocol: org.apache.hadoop.hdfs.server.protocol.NamenodeProtocol
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.getProtocolImpl(ProtobufRpcEngine.java:444)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:502)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:906)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:852)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1876)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2753)

	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1516)
	at org.apache.hadoop.ipc.Client.call(Client.java:1462)
	at org.apache.hadoop.ipc.Client.call(Client.java:1372)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
	at com.sun.proxy.$Proxy11.versionRequest(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.NamenodeProtocolTranslatorPB.versionRequest(NamenodeProtocolTranslatorPB.java:162)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.getBlockPoolId(NNThroughputBenchmark.java:1558)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.run(NNThroughputBenchmark.java:1531)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.runBenchmark(NNThroughputBenchmark.java:1438)
	at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.main(NNThroughputBenchmark.java:1563)
```

Proxy:

```bash
gangl@linuxkit-025000000001:~/hadoop/hadoop-dist/target/hadoop-3.3.0-SNAPSHOT$ ./bin/hadoop jar  /home/gangl/hadoop/hadoop-hdfs-project/hadoop-hdfs-nnproxy/target/hadoop-hdfs-nnproxy-1.0.0.jar org.apache.hadoop.hdfs.nnproxy.server.ProxyMain
2019-09-06 05:10:02,294 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
2019-09-06 05:10:02,598 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
2019-09-06 05:10:02,598 INFO impl.MetricsSystemImpl: NNProxy metrics system started
2019-09-06 05:10:04,812 INFO ipc.CallQueueManager: Using callQueue: class java.util.concurrent.LinkedBlockingQueue, queueCapacity: 204800, scheduler: class org.apache.hadoop.ipc.DefaultRpcScheduler, ipcBackoff: false.
2019-09-06 05:10:05,038 INFO ipc.Server: Starting Socket Reader #1 for port 65212
2019-09-06 05:10:05,997 INFO ipc.Server: IPC Server Responder: starting
2019-09-06 05:10:05,998 INFO ipc.Server: IPC Server listener on 65212: starting
2019-09-06 05:10:06,604 INFO server.NNProxy: Started nnproxy...
2019-09-06 05:12:30,918 INFO ipc.Server: IPC Server handler 1645 on default port 65212, call Call#0 Retry#0 org.apache.hadoop.hdfs.server.protocol.NamenodeProtocol.versionRequest from 127.0.0.1:43992
org.apache.hadoop.ipc.RpcNoSuchProtocolException: Unknown protocol: org.apache.hadoop.hdfs.server.protocol.NamenodeProtocol
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.getProtocolImpl(ProtobufRpcEngine.java:444)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:502)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:906)
	at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:852)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1876)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2753)
^C2019-09-06 05:12:47,610 INFO server.NNProxy: Gracefully shutting down nnproxy...
2019-09-06 05:12:48,616 INFO ipc.Server: Stopping server on 65212
2019-09-06 05:12:49,171 INFO ipc.Server: Stopping IPC Server listener on 65212
2019-09-06 05:12:49,172 INFO ipc.Server: Stopping IPC Server Responder
2019-09-06 05:12:49,171 INFO server.NNProxy: NNProxy shutdown completed
2019-09-06 05:12:49,172 INFO server.ProxyMain: NNProxy halted
```

**Comment by gangliao** [comment]
I have to extend NameNodeProtocal....   #cry....

**Comment by gangliao** [comment]
No，just change benchmark is good enough
