### ISSUE TITLE
java.lang.Long cannot be cast to java.lang.Short

### ISSUE THREAD

**Issue by gangliao** [DSL-UMD/hadoop#21]
```bash
e.Ne.Ne.Nnamenode.N.namenode.Nr.namenode.NNThroughputBenchmark -fs hdfs://localhost:9000 -op blockReport -datanodes 1 -reports 1 esu-b esu-keesuepResulocksPerR3 -keepResueport 1 -b 3 -keepResulocksPerFile 3 -keepResults -logLevel INFO
2019-03-12 23:44:39,001 INFO namenode.NNThroughputBenchmark: Starting benchmark: blockReport
2019-03-12 23:44:39,384 INFO namenode.NNThroughputBenchmark: Creating 1 files with 3 blocks each.
2019-03-12 23:44:40,962 INFO db.DatabaseConnection: DatabaseConnection: [OK] Create inodes, inode2block and datablocks in db.
2019-03-12 23:44:41,030 INFO db.DatabaseDatablock: generationStamp [GET]: (1073741825,1001)
2019-03-12 23:44:41,032 INFO db.DatabaseDatablock: numBytes [GET]: (1073741825,0)
2019-03-12 23:44:41,070 INFO db.DatabaseDatablock: numBytes [GET]: (1073741825,0)
2019-03-12 23:44:41,072 INFO db.DatabaseDatablock: generationStamp [GET]: (1073741825,1001)
2019-03-12 23:44:41,330 INFO db.DatabaseDatablock: generationStamp [GET]: (1073741826,1002)
2019-03-12 23:44:41,332 INFO db.DatabaseDatablock: numBytes [GET]: (1073741826,0)
2019-03-12 23:44:41,337 INFO db.DatabaseDatablock: numBytes [GET]: (1073741826,0)
2019-03-12 23:44:41,339 INFO db.DatabaseDatablock: generationStamp [GET]: (1073741826,1002)
2019-03-12 23:44:41,683 INFO db.DatabaseDatablock: generationStamp [GET]: (1073741827,1003)
2019-03-12 23:44:41,689 INFO db.DatabaseDatablock: numBytes [GET]: (1073741827,0)
2019-03-12 23:44:41,707 INFO db.DatabaseDatablock: numBytes [GET]: (1073741827,0)
2019-03-12 23:44:41,710 INFO db.DatabaseDatablock: generationStamp [GET]: (1073741827,1003)
2019-03-12 23:44:41,880 ERROR namenode.NNThroughputBenchmark: org.apache.hadoop.ipc.RemoteException(java.lang.ClassCastException): j: j: j: jeption): jception): jxception): java.lang.Long cannot be cast to java.lang.Short
        at org.apache.hadoop.hdfs.db.DatabaseDatablock.getReplication(DatabaseDatablock.java:121)
        at org.apache.hadoop.hdfs.server.blockmanagement.BlockInfo.getReplication(BlockInfo.java:88)
        at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.getExpectedRedundancyNum(BlockManager.java:4525)
        at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.checkRedundancy(BlockManager.java:4403)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.finalizeINodeFileUnderConstruction(FSNamesystem.java:3601)
        at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFileInternal(FSDirWriteFileOp.java:743)
        at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFile(FSDirWriteFileOp.java:693)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:2942)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:943)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTdeTdeTdeTerverSideTServerSideTlServerSideTranslatorPB.java:613)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNameameameameClientName(ClientNamed(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:898)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:844)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1876)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2727)

        at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1511)
        at org.apache.hadoop.ipc.Client.call(Client.java:1457)
        at org.apache.hadoop.ipc.Client.call(Client.java:1367)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
        at com.sun.proxy.$Proxy9.complete(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:553553553553B.java:553PB.java:553rPB.java:553)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
        at com.sun.proxy.$Proxy10.complete(Unknown Source)
        at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark$BlockReportStats.generateInputs(NNThroughputBenchmark.java:1a:1a:1a:1ark.java:1mark.java:1hmark.java:1147)
        at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark$OperationStatsBase.benchmark(NNThroughputBenchmark.java:258)
        at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.run(NNThroughputBenchmark.java:1531)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
        at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.runBenchmark(NNThroughputBenchmark.java:1432)
        at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.main(NNThroughputBenchmark.java:1556)

Exception in thread "main" org.apache.hadoop.ipc.RemoteException(java.lang.ClassCastException): java.lang.Long cannot be cast to javjavjavjavast to javcast to jav cast to java.lang.Short
        at org.apache.hadoop.hdfs.db.DatabaseDatablock.getReplication(DatabaseDatablock.java:121)
        at org.apache.hadoop.hdfs.server.blockmanagement.BlockInfo.getReplication(BlockInfo.java:88)
        at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.getExpectedRedundancyNum(BlockManager.java:4525)
        at org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.checkRedundancy(BlockManager.java:4403)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.finalizeINodeFileUnderConstruction(FSNamesystem.java:3601)
        at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFileInternal(FSDirWriteFileOp.java:743)
        at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.completeFile(FSDirWriteFileOp.java:693)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.completeFile(FSNamesystem.java:2942)
        at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.complete(NameNodeRpcServer.java:943)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.complete(ClientNamenodeProtocolServerSideTdeTdeTdeTerverSideTServerSideTlServerSideTranslatorPB.java:613)
        at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNameameameameClientName(ClientNamed(ClientNamenodeProtocolProtos.java)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:524)
        at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1025)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:898)
        at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:844)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1876)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2727)

        at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1511)
        at org.apache.hadoop.ipc.Client.call(Client.java:1457)
        at org.apache.hadoop.ipc.Client.call(Client.java:1367)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:228)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:116)
        at com.sun.proxy.$Proxy9.complete(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.complete(ClientNamenodeProtocolTranslatorPB.java:553553553553B.java:553PB.java:553rPB.java:553)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
        at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
        at com.sun.proxy.$Proxy10.complete(Unknown Source)
        at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark$BlockReportStats.generateInputs(NNThroughputBenchmark.java:1a:1a:1a:1ark.java:1mark.java:1hmark.java:1147)
        at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark$OperationStatsBase.benchmark(NNThroughputBenchmark.java:258)
        at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.run(NNThroughputBenchmark.java:1531)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
        at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.runBenchmark(NNThroughputBenchmark.java:1432)
        at org.apache.hadoop.hdfs.server.namenode.NNThroughputBenchmark.main(NNThroughputBenchmark.java:1556)
gangl@linuxkit-025000000001:~/hadoop/hadoop-dist/target/hadoop-3.3.0-SNAPSHOT$ kill $(jps | grep '[NameNode,DataNode]' | awk '{print $1}')
```

**Comment by gangliao** [comment]
```bash
docker=# select * from datablocks;
  blockid   | numbytes | generationstamp | replication
------------+----------+-----------------+-------------
          0 |        0 |               0 |
 1073741825 |        0 |            1001 |           1
 1073741826 |        0 |            1002 |           1
 1073741827 |        0 |            1003 |           1
(4 rows)

docker=# select * from inodes;
  id   | parent |         name          |  accesstime   | modificationtime |     header      |  permission
-------+--------+-----------------------+---------------+------------------+-----------------+---------------
 16385 |      0 |                       |             0 |    1552434279578 |               0 | 1099511693805
 16386 |  16385 | nnThroughputBenchmark |             0 |    1552434279637 |               0 | 1099511693805
 16387 |  16386 | blockReport           |             0 |    1552434279698 |               0 | 1099511693805
 16388 |  16387 | ThroughputBenchDir0   |             0 |    1552434279733 |               0 | 1099511693805
 16389 |  16388 | ThroughputBench0      | 1552434279733 |    1552434281838 | 281474976710672 | 1099511693823
(5 rows)

docker=# select * from inode2block;
  blockid   |  id   | index
------------+-------+-------
 1073741825 | 16389 |     0
 1073741826 | 16389 |     1
 1073741827 | 16389 |     2
(3 rows)

```
